version: "3.9"

services:
  web:
    image: nginx:1.24-alpine3.17-slim
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/develop/default.no-cache.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/develop/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - frontend

  redis:
    build:
      context: ./redis/develop

  php:
    build:
      context: ./php/develop
    volumes:
      - ..:/var/www/html
    depends_on:
      - redis
      - mysql
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:8.3.0
    ports:
      - "8306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: stockpress
      MYSQL_PASSWORD: stockpress
      MYSQL_DATABASE: stockpress
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  mysql-test:
    image: mysql:8.3.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: stockpress-test
      MYSQL_PASSWORD: stockpress-test
      MYSQL_DATABASE: stockpress-test
    networks:
      - backend
    tmpfs:
      - /var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  mysql-data:
