version: "3.9"

services:
  web:
    image: nginx:1.24-alpine3.17-slim
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/develop/default.no-cache.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/develop/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php

  redis:
    build:
      context: ./redis/develop

  php:
    build:
      context: ./php/develop
    volumes:
      - ..:/var/www/html
    depends_on:
      - redis
